# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_ti',
            new_name='valid_to',
        ),
    ]
